language: go

go:
  - 1.5.4
  - 1.6.3
  - 1.7.1
  - tip

sudo: false

install:
  - go get github.com/Masterminds/glide
  - GO15VENDOREXPERIMENT=1 go build

script:
  - GO15VENDOREXPERIMENT=1 go test .

