version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\sgotti\glide-vc
shallow_clone: true

environment:
  GOPATH: C:\gopath

platform:
- x64

install:
- go version
- go env

build_script:
- go get

test_script:
- go test ./...

deploy: off
